server.port=8888
spring.application.name=config-server

# Eureka (so config server registers itself)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

autoconfigure.exclude=org.springframework.cloud.config.client.ConfigServiceBootstrapConfiguration

)
# Replace with your repo path and branch
spring.cloud.config.server.git.uri=file://${user.home}/suividoctorat-config-repo
spring.cloud.config.server.git.search-paths=.
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main



