server.port=8888
spring.application.name=config-server

# Eureka (so config server registers itself)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

autoconfigure.exclude=org.springframework.cloud.config.client.ConfigServiceBootstrapConfiguration

# Use native filesystem backend to read config files directly from workspace (no git clone)
spring.profiles.active=native
spring.cloud.config.server.native.searchLocations=file:${project.basedir}/../config-repo
spring.cloud.config.server.native.failOnMissingLocation=false



